sonar.organization=mahnoor-tariq
sonar.projectKey=mahnoor-mern-10pshine
sonar.projectName=mahnoor-mern-10pshine
sonar.sourceEncoding=UTF-8

# Scan both frontend and backend
sonar.sources=frontend/src,backend/src

# Exclude test files and node_modules
sonar.exclusions=**/node_modules/**,**/*.test.*,**/coverage/**

# Include both coverage reports
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
